BEGIN 

 MERGE INTO T_EQU_SAPF sapf USING (
        SELECT SAPOD, SABRNM, SAPBR, SAPSQ, (SAAMA / C8PWD * C8SPT) SAAMA_PLN
        FROM T_EQU_SAPF
        INNER JOIN T_EQU_HC8PF ON HCDTE = SAPOD AND C8CCY = SACCY
        WHERE  SAAMA_PLN IS NULL AND  "SAVFR" >= (SELECT To_Date('01-12-2014','dd-mm-yyyy') FROM dual) AND "SAVFR" <= (SELECT To_Date('31-12-2014','dd-mm-yyyy') FROM dual)
    ) "Data" ON (sapf.SAPOD = "Data".SAPOD and sapf.SABRNM = "Data".SABRNM and sapf.SAPBR = "Data".SAPBR and sapf.SAPSQ = "Data".SAPSQ)
    WHEN MATCHED THEN
        UPDATE SET SAAMA_PLN = "Data".SAAMA_PLN;
		

update T_EQU_SAPF set SAAMA_PLN = SAAMA /(select C8PWD  from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY) * (select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-25','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-05','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-05','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-06','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-19','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-19','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-21','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-28','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-19','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-19','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-20','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-05','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-05','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-07','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-11-21','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-11-21','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-11-23','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-12','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-12','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-13','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-31','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-31','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2015-01-01','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-26','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-11-28','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-11-28','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-11-30','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-19','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-19','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-20','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-12','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-12','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-13','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-25','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-11-28','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-11-28','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-11-29','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-19','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-19','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-21','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-25','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-12','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-12','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-14','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-27','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-12','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-12','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-14','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-12','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-12','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-14','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-11-28','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-11-28','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-11-29','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-28','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-11-28','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-11-28','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-11-29','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-05','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-05','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-07','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-05','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-05','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-06','YYYY-MM-DD');
update T_EQU_SAPF set SAAMA_PLN = SAAMA / (select C8PWD from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY)*(select  C8SPT from  T_EQU_HC8PF where HCDTE = to_date('2014-12-24','YYYY-MM-DD') AND C8CCY = SACCY) WHERE  SAAMA_PLN IS NULL  and sapod  >= to_date('01/12/2014','DD/MM/YYYY') and sapod = to_date('2014-12-26','YYYY-MM-DD');
		

END;